[package]
name = "mdga-brnfck"
version = "0.1.0"
authors = ["alexeales <alex.eales@potatolondon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
